import React from 'react';
import { 
    ChevronLeft, 
    ChevronRight, 
    ChevronDown,
    ChevronUp,
    ChevronsUp,
    Pencil, 
    X, 
    LogOut, 
    Calendar, 
    Bell, 
    MessageSquare,
    MapPin,
    Check,
    AlertCircle,
    User,
    UserPlus,
    Users,
    CheckCircle2,
    Loader2,
    Clock,
    XCircle,
    Camera,
    Search,
    Plus,
    PlusCircle,
    Trash2,
    Eye,
    EyeOff,
    Sun,
    Moon,
    Briefcase,
    LayoutGrid,
    ClipboardList,
    CreditCard,
    QrCode,
    Shield,
    DollarSign,
    Zap,
    Percent,
    Minus,
    Save,
    ArrowLeft,
    ArrowRight,
    Grid,
    Menu,
    ConciergeBell,
    RotateCw,
    Printer,
    Image,
    TrendingUp,
    TrendingDown,
    Package,
    Inbox,
    Coins,
    ShoppingBag,
    Home,
    Soup,
    Flame,
    CupSoda,
    Table,
    Coffee,
    Pizza,
    Beef,
    Leaf,
    Fish,
    Cake,
    Wine,
    Beer,
    Utensils
} from 'lucide-react';

export const ICONS = {
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    chevronsUp: ChevronsUp,
    pencil: Pencil,
    close: X,
    logout: LogOut,
    calendar: Calendar,
    bell: Bell,
    message: MessageSquare,
    mapPin: MapPin,
    check: Check,
    alert: AlertCircle,
    user: User,
    userPlus: UserPlus,
    users: Users,
    checkCircle: CheckCircle2,
    spinner: Loader2,
    clock: Clock,
    xCircle: XCircle,
    camera: Camera,
    search: Search,
    plus: Plus,
    plusCircle: PlusCircle,
    trash: Trash2,
    eye: Eye,
    eyeOff: EyeOff,
    sun: Sun,
    moon: Moon,
    briefcase: Briefcase,
    layoutGrid: LayoutGrid,
    clipboardList: ClipboardList,
    creditCard: CreditCard,
    qrCode: QrCode,
    shield: Shield,
    dollarSign: DollarSign,
    zap: Zap,
    percent: Percent,
    minus: Minus,
    save: Save,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    grid: Grid,
    menu: Menu,
    conciergeBell: ConciergeBell,
    refresh: RotateCw,
    printer: Printer,
    image: Image,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    package: Package,
    inbox: Inbox,
    coins: Coins,
    shoppingBag: ShoppingBag,
    home: Home,
    soup: Soup,
    flame: Flame,
    drink: CupSoda,
    table: Table,
    coffee: Coffee,
    pizza: Pizza,
    meat: Beef,
    leaf: Leaf,
    fish: Fish,
    dessert: Cake,
    wine: Wine,
    beer: Beer,
    utensils: Utensils
};

export default function Icon({ name, className = '', size = 18, strokeWidth = 2.5, ...props }) {
    const Component = ICONS[name];
    if (!Component) return null;
    return <Component className={className} size={size} strokeWidth={strokeWidth} {...props} />;
}
